### ISSUE TITLE
New minor version  1.3.7 introduces a breaking changes

### ISSUE THREAD

**Issue by ThomasKientz** [npm/ini#103]
Use of `Object.create(null)` in [this commit ](https://github.com/npm/ini/commit/032fbaf5f0b98fce70c8cc380e0d05177a9c9073) breaks the use of `hasOwnProperty()` by other packages depending on this one.

Eg : https://github.com/jonschlinkert/git-user-email/pull/5

I am suggesting a rollback and publishing that change as a major version bump instead.

**Comment by isaacs** [comment]
Ack, good catch, sorry about that.

Fixed on 1.3.8, I'll publish a v2 shortly that re-introduces the change.  (For what it's worth, relying on `obj.hasOwnProperty` is a bit brittle anyway, because someone could put a `hasOwnProperty` field in the ini file itself.)j
