### ISSUE TITLE
[BUG] Prototype Pollution [High Severity]

### ISSUE THREAD

**Issue by mattpilleul** [npm/ini#104]
# What / Why
High Severity security issue with ini@1.3.5

## When
* Whenever I launch a Snyk Dependencies Audit.

### Current Behavior
* Can't user bcrypt@5.0.0 with this current security issue.

### Images
[https://postimg.cc/vxRg3cHg](url) | **Snyk Audit**
[https://postimg.cc/Zvr9g4Cf](url) | **Yarn.lock**

**Comment by ExE-Boss** [comment]
This was fixed in [v1.3.6](https://github.com/npm/ini/releases/tag/v1.3.6) (<https://github.com/npm/ini/commit/56d2805e07ccd94e2ba0984ac9240ff02d44b6f1>).
