### ISSUE TITLE
npm package links to old repo location

### ISSUE THREAD

**Issue by smichel17** [npm/ini#122]
FYI — https://www.npmjs.com/package/ini still links to https://github.com/isaacs/ini, rather than https://github.com/npm/ini

**Comment by codemaster138** [comment]
It does, but that repo redirects here so it really doesn‘t matter

**Comment by azooz-12** [comment]
**axxc414@gmail.com
**

**Comment by wraithgar** [comment]
```sh
~/D/n/ini (main|✔) $ npm view ini repository
{ type: 'git', url: 'git+https://github.com/npm/ini.git' }
```
