### ISSUE TITLE
REQUEST: add option to preserve comments

### ISSUE THREAD

**Issue by phun-ky** [npm/ini#32]
I'm using `ini` to parse a nexus deploy configuration file, and by all means, it works great, but our java developers has the habit of using comments in this configuration file, and `ini.parse` removes all text after strings with `#` and `;`. 
#### Desired outcome:

```
# Supports interpolation
# Can reference other values in same section or in special default section
# To reference myValue, you need to write: %(myValue)s

[DEFAULT]
....
syslog.local0.levels=info;error
```
#### Actual outcome:

```
[DEFAULT]
....
syslog.local0.levels=info
```

_I'm using `ini@1.3.0`, `npm@1.4.3` and `nodejs@0.10.26` in a windows 7 environment with git bash_

**Comment by gavinengel** [comment]
+1 I'd like this all well.  Basically what I want is a way to make simple edits to ini/cnf files on the Linux CLI.      I want to ensure that comments are retained.  Perhaps using this method: http://fadefade.com/json-comments.html  or perhaps into cson?

**Comment by exse2** [comment]
hello person from 2014.
just use this and call it a day:


npm install --save --no-package-lock --unsafe-perm=true ini-api


	  import fs from 'fs';
	  import iniApi from 'ini-api';
	  const Ini = iniApi.Ini;
	  
	  (async () => {
		  let text = fs.readFileSync('/etc/systemd/journald.conf', 'utf-8');
		  let ini = new Ini(text);
		  ini.getSection('Journal').setValue('Storage', 'persistent');
		  fs.writeFileSync('./config_modified.ini', ini.stringify())
	  })();

it retains comments.

**Comment by wraithgar** [comment]
If this is still something folks need feel free to submit a PR implementing the feature.
