### ISSUE TITLE
Encode values without quoting (unsafe encoding)

### ISSUE THREAD

**Issue by schroffl** [npm/ini#57]
When encoding a Base64 String with padding, the parser quotes it. But since another parser does not understand these quotes, it fails to decode the string.  

``` javascript
let buf = new Buffer(16), // Buffer filled with random bytes
    section = ini.parse('[section]\nkey=' + buf.toString());

console.log(section); // { section: { key: 'UPIvqf0AAABA5i+p/QAAAA==' } }
console.log(encode(section)); // key="4EQ8rlYAAAAQlTWuVgAAAA=="
```

Hence I suggest to add an option to allow for unsafe encoding.

**Comment by curcuz** [comment]
+1

**Comment by jurijzahn8019** [comment]
I would like to have the option too, since safe breaks aws credentials file

**Comment by m417z** [comment]
You can try my fork, [ini-win](https://www.npmjs.com/package/ini-win), which aims to be more compatible with the way Windows handles ini files. It quotes the value only in two cases, if the value has leading or trailing whitespace, or if the value is already quoted.

**Comment by dertanzer** [comment]
> You can try my fork, [ini-win](https://www.npmjs.com/package/ini-win), which aims to be more compatible with the way Windows handles ini files. It quotes the value only in two cases, if the value has leading or trailing whitespace, or if the value is already quoted.

Thanks for your fork!

**Comment by wraithgar** [comment]
If this is something folks still need feel free to submit a PR implementing this flag.

**Comment by milesstoetzner** [comment]
The underlying problem is that `safe` does parse a string which contains a `=` with `JSON.stringify` due to `val.match(/[=\r\n]/)` in 

https://github.com/npm/ini/blob/c89e2090d7989bb91255ec46eaaf5f8cb1c34b34/lib/ini.js#L217-L228
