### ISSUE TITLE
str.split is not a function 

### ISSUE THREAD

**Issue by NikosEfthias** [npm/ini#59]
![](http://i.imgur.com/lneZ1CM.png)

**Comment by Klathmon** [comment]
For anyone else that gets this, it's because you are giving it a buffer and not a string.

Changing something like `fs.readFileSync('filename.ini')` to `fs.readFileSync('filename.ini', 'utf-8')` will fix the problem.

**Comment by NikosEfthias** [comment]
eventually i figured that out thats why i closed the bug report :) thanks @Klathmon
