### ISSUE TITLE
Section headers with '.' in them are split

### ISSUE THREAD

**Issue by ankon** [npm/ini#60]
I have the following .ini file:

```
[https://www.example.com]
settingA = foo
settingB = bar
```

When parsing this .ini the resulting structure has the section header cut into pieces, I expected `{'https://www.example.com': { settingA: 'foo', settingB: 'bar' } }`, but got `{'https://www': { 'example': { 'com':  { settingA: 'foo', settingB: 'bar' } } } }`.

**Comment by ankon** [comment]
Reading through the `test` directory it seems this is a feature, not a bug. Maybe it would be worthwhile to be more explicit about it in the documentation, especially also how to try to escape the values (the source of the .ini file seems to actually be happy with me escaping the '.' characters using a '\').

**Comment by platinumazure** [comment]
For what it's worth, I'm working on a PR for this, but it will be a few days or weeks before I submit it.

**Comment by BamButz** [comment]
What's the status on this? I would also need the functionality to skip the splitting.

**Comment by ext** [comment]
I've hit this bug as well, I would be fine with a way to disable splitting instead of changing the delimiter but as it is right now this is preventing me from using this library but I cant find any other useful ini parser either.

**Comment by rehanvdm** [comment]
Just post process the data, I provided a solution here https://github.com/npm/ini/issues/22#issuecomment-1426581205 (can probably be improved but it works. I don't foresee the creators of the package changing it anytime soon they are strictly following the ini specification.
