### ISSUE TITLE
How to set listen and listen.owner ...?

### ISSUE THREAD

**Issue by goldingdamien** [npm/ini#79]
In the link below, listen and listen.owner , etc. exist. Due to an object not be able to be {listen: val1} and {listen: {user: val2}} at the same time what should be done?

https://gist.github.com/mustafaturan/3942448

**Comment by wraithgar** [comment]
That's not possible because that is not how this module interprets objects.  `[]` headings are the only way to achieve this `key=value` pairs will always result in a literal `key` as given.
