### ISSUE TITLE
=true being outputted after parse, stringify.

### ISSUE THREAD

**Issue by goldingdamien** [npm/ini#80]
Doing parse, stringify using the ini below, results in a line using an empty key as below:

...
listen = 127.0.0.1:9000
=true
listen.allowed_clients = 127.0.0.1
...

Why does it become "=true"?

https://gist.github.com/mustafaturan/3942448

**Comment by Cevastes** [comment]
i am having the same

**Comment by wraithgar** [comment]
Fixed by https://github.com/npm/ini/pull/201
