### ISSUE TITLE
Please add a description of node usage

### ISSUE THREAD

**Issue by minhhn0205** [npm/ini#97]
Currently this node [https://flows.nodered.org/node/node-red-contrib-parser-ini](url) does not have any documentation.
If possible please add documentation as a description of node usage.

**Comment by GrosSacASac** [comment]
It is another project. Open issue here https://github.com/alexandrainst/node-red-contrib-parser-ini

**Comment by wraithgar** [comment]
Looks like the readme does have usage examples now.
